### ISSUE TITLE
In chapter03 StatusCodePages demo and the explanation in the book is wrong?

### ISSUE THREAD

**Issue by sgal008** [andrewlock/asp-dot-net-core-in-action#13]
![image](https://user-images.githubusercontent.com/42566429/72523041-ed438b80-3899-11ea-8c03-f9991a569933.png)
Shouldn't it be `app. Usestatuscodepage();` and `app. Usestatuscodepageswithreexecute ("/ error / {0}");` here?

**Comment by sgal008** [comment]
I see your blog [Re-execute the middleware pipeline with the StatusCodePages Middleware to create custom error pages](https://andrewlock.net/re-execute-the-middleware-pipeline-with-the-statuscodepages-middleware-to-create-custom-error-pages/) solved my question!

**Comment by andrewlock** [comment]
Hi, apologies @sgal008, you're right. The code in the 2.0 folder is incorrect - it looks like it wasn't converted correctly from the 1.0 version. 

I've just pushed an update to correct the issue.

Thanks!
