### ISSUE TITLE
Question: Is there any roadmap for the next release of the book?

### ISSUE THREAD

**Issue by sadqiang** [andrewlock/asp-dot-net-core-in-action#2]
I like your book very much and I noticed there are some changes in the latest asp.net core and of course the incoming asp.net core 3.0.

Is there any roadmap for the next release of your book?

**Comment by andrewlock** [comment]
Hi , thanks, I appreciate it! I'm afraid I don't have any information regarding updates. It's very hard to know how big of an impact .NET Core 3.0 will be at the moment, but the updates in 2.x apps are relatively minimal. The book doesn't cover everything in the framework obviously, but what it does cover is generally accurate for all 2.x versions of the framework
